openapi: 3.0.3
info:
  title: Ingredients API
  version: 1.0.0

servers:
  - url: http://localhost:3000/v1
    description: Local développement

paths:
  /ingredients:
    get:
      summary: Liste des ingrédients
      responses:
        '200':
          description: Retourne la liste des ingrédients enregistrés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
                example:
                  - id: 1
                    nom: Laitue
                    categorie: Vegetable
                    prix: 800.00
                  - id: 2
                    nom: Tomate
                    categorie: Vegetable
                    prix: 600.00
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: string
              example: "Erreur du chargement de la liste des ingrédients"

  /ingredients/{id}:
    get:
      summary: Récupération d'un ingrédient
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de l'ingrédient
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Ingredient récupéré
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
              example:
                - id: 2
                  nom: Poulet
                  categorie: Animal
                  prix: 56.2
        '404':
          description: Erreur lors du chargement de l'ingrédient
          content:
            application/json:
              schema:
                type: string
              example: "Ingredient.id={2} n'est pas trouvé"


  /ingredients/{id}/stock:
    get:
      summary: Retourne le stock d'un ingrédient
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant de l'ingrédient
          schema:
            type: integer
            example: 2
        - name: at
          in: query
          required: true
          description: Moment auquel récupérer le stock
          schema:
            type: string
            example: "2024-01-15T10:00:00Z"
        - name: unit
          in: query
          required: true
          description: Unité du stock
          schema:
            type: string
            enum: [PCS, KG, L]
            example: KG
      responses:
        '200':
          description: Stock trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
              example:
                unit: KG
                valeur: 25.5
        '400':
          description: Paramètre manquant
          content:
            application/json:
              schema:
                type: string
              example: "Either mandatory query parameter `at` or `unit` is not provided."
        '404':
          description: Ingrédient non trouvé
          content:
            application/json:
              schema:
                type: string
              example: "Ingredient.id=2 is not found"

  /dishes:
    get:
      summary: Retourne la liste des plats
      responses:
        '200':
          description: Liste des plats enregistrés en base
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
              example:
                - id: 23
                  nom: Pain choco
                  prixPlat: 1000.00
                  ingredients:
                    - id: 1
                      nom: Laitue
                      categorie: Vegetable
                      prix: 800.00
                    - id: 2
                      nom: Tomate
                      categorie: Vegetable
                      prix: 600.00
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: string
              example: "Error to recover list of dishes"



components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          description: Identifiant de l'ingrédient
        nom:
          type: string
          description: Nom de l'ingrédient
        categorie:
          type: string
          description: Catégorie de l'ingrédient
        prix:
          type: number
          description: Prix de l'ingrédient

    Stock:
      type: object
      properties:
        unit:
          type: string
          enum: [PCS, KG, L]
          description: Unité du stock
        valeur:
          type: number
          description: Valeur du stock

    Dish:
      type: object
      properties:
        id:
          type: integer
          description: Identifiant
        nom:
          type: string
          description: Nom du plat
        prixPlat:
          type: number
          description: Prix de vente
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
          description: Liste des ingrédients